import re
import sqlite3

from config import DATABASE_PATH, DATABASE_TYPE, DATABASE_URL

if DATABASE_TYPE == "postgres":
    import psycopg

# ---------------------------------------------------------------------------
# Schema (SQLite dialect). For PostgreSQL the annotation id line uses a
# different primary key definition (see _schema()).
# ---------------------------------------------------------------------------

_SCHEMA = [
    """CREATE TABLE IF NOT EXISTS fyndnote_users (
        id          TEXT PRIMARY KEY,
        name        TEXT NOT NULL,
        global_role TEXT NOT NULL CHECK(global_role IN ('system_admin','annotator')),
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )""",
    """CREATE TABLE IF NOT EXISTS fyndnote_projects (
        id          TEXT PRIMARY KEY,
        name        TEXT NOT NULL,
        dataset_id  TEXT NOT NULL,
        template_id TEXT NOT NULL,
        salt        TEXT NOT NULL,
        color       TEXT DEFAULT '#1976d2',
        tags        TEXT DEFAULT '',
        instructions TEXT DEFAULT '',
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )""",
    """CREATE TABLE IF NOT EXISTS fyndnote_project_permissions (
        user_id    TEXT NOT NULL REFERENCES fyndnote_users(id),
        project_id TEXT NOT NULL REFERENCES fyndnote_projects(id),
        role       TEXT NOT NULL CHECK(role IN ('project_admin','annotator')),
        PRIMARY KEY (user_id, project_id)
    )""",
    """CREATE TABLE IF NOT EXISTS fyndnote_annotations (
        id         {pk},
        project_id TEXT NOT NULL REFERENCES fyndnote_projects(id),
        row_index  INTEGER NOT NULL,
        user_id    TEXT NOT NULL REFERENCES fyndnote_users(id),
        data       TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(project_id, row_index, user_id)
    )""",
    """CREATE TABLE IF NOT EXISTS fyndnote_ml_annotations (
        project_id TEXT NOT NULL REFERENCES fyndnote_projects(id),
        row_index  INTEGER NOT NULL,
        annotator  TEXT NOT NULL,
        data       TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(project_id, row_index)
    )""",
    """CREATE TABLE IF NOT EXISTS fyndnote_datasets (
        id            TEXT PRIMARY KEY,
        source        TEXT NOT NULL,
        source_type   TEXT NOT NULL,
        source_format TEXT,
        hf_name       TEXT,
        hf_split      TEXT,
        num_rows      INTEGER NOT NULL,
        columns       TEXT NOT NULL,
        created_at    TEXT NOT NULL,
        s3_uploaded   INTEGER DEFAULT 0
    )""",
    """CREATE TABLE IF NOT EXISTS dataset_meta (
        project_id   TEXT PRIMARY KEY,
        num_rows     INTEGER NOT NULL DEFAULT 0,
        next_fragment INTEGER NOT NULL DEFAULT 0,
        schema       TEXT,
        created_at   TEXT NOT NULL
    )""",
]

_SQLITE_PK = "INTEGER PRIMARY KEY AUTOINCREMENT"
_PG_PK = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

# Conflict target for tables that use "INSERT OR REPLACE" (SQLite) so we can
# translate it to PostgreSQL "ON CONFLICT (...) DO UPDATE SET".
_OR_REPLACE_TARGETS = {"fyndnote_ml_annotations": ["project_id", "row_index"]}

_OR_REPLACE_RE = re.compile(
    r"INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*(.*)$",
    re.IGNORECASE | re.DOTALL,
)


def _schema():
    pk = _SQLITE_PK if DATABASE_TYPE == "sqlite" else _PG_PK
    return [s.format(pk=pk) for s in _SCHEMA]


# ---------------------------------------------------------------------------
# Row wrapper for PostgreSQL: supports row["col"], row[0], row.keys() and
# dict(row), mirroring sqlite3.Row.
# ---------------------------------------------------------------------------


class _Row:
    __slots__ = ("_cols", "_m")

    def __init__(self, mapping):
        self._m = mapping
        self._cols = list(mapping.keys())

    def __getitem__(self, k):
        if isinstance(k, int):
            return self._m[self._cols[k]]
        return self._m[k]

    def keys(self):
        return list(self._cols)

    def __iter__(self):
        return iter(self._m.values())

    def __len__(self):
        return len(self._m)


def _pg_row_factory(cur):
    cols = [d.name for d in cur.description] if cur.description else []

    def make(values):
        return _Row(dict(zip(cols, values)))

    return make


class _NoResult:
    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def fetchmany(self, n=0):
        return []


class _PGConnection:
    def __init__(self, url):
        self.conn = psycopg.connect(url)
        self.conn.row_factory = _pg_row_factory

    def execute(self, sql, params=None):
        sql = _translate(sql)
        if sql is None:  # PRAGMA / SQLite-only statement
            return _NoResult()
        sql = sql.replace("?", "%s")  # psycopg3 uses %s placeholders
        return self.conn.execute(sql, params or ())

    def commit(self):
        self.conn.commit()

    def close(self):
        self.conn.close()


# ---------------------------------------------------------------------------
# SQLite -> PostgreSQL translation for the few SQLite-only constructs used.
# ---------------------------------------------------------------------------


def _translate_replace(sql):
    m = _OR_REPLACE_RE.match(sql.strip())
    if not m:
        return sql.replace("INSERT OR REPLACE INTO", "INSERT INTO", 1)
    table = m.group(1)
    cols = [c.strip() for c in m.group(2).split(",")]
    values = m.group(3).strip()
    target = _OR_REPLACE_TARGETS.get(table)
    if target is None:
        return sql.replace("INSERT OR REPLACE INTO", "INSERT INTO", 1)
    set_cols = ", ".join(f"{c}=EXCLUDED.{c}" for c in cols if c not in target)
    return (
        f"INSERT INTO {table} ({', '.join(cols)}) VALUES {values} "
        f"ON CONFLICT ({', '.join(target)}) DO UPDATE SET {set_cols}"
    )


def _translate(sql):
    s = sql.strip()
    if s.startswith("PRAGMA"):
        return None
    # SQLite -> PostgreSQL: json_extract(data, '$.x') -> data::jsonb ->> '$.x'
    s = s.replace("json_extract(data, ?)", "data::jsonb ->> ?")
    if "INSERT OR IGNORE INTO" in s:
        s = s.replace("INSERT OR IGNORE INTO", "INSERT INTO", 1).strip()
        return s + " ON CONFLICT DO NOTHING"
    if "INSERT OR REPLACE INTO" in s:
        return _translate_replace(s)
    return s


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_db():
    if DATABASE_TYPE == "sqlite":
        db = sqlite3.connect(str(DATABASE_PATH))
        db.row_factory = sqlite3.Row
        return db
    return _PGConnection(DATABASE_URL)


def init_db():
    db = get_db()
    if DATABASE_TYPE == "sqlite":
        db.execute("PRAGMA journal_mode=WAL")
        db.execute("PRAGMA foreign_keys=ON")
    for ddl in _schema():
        db.execute(ddl)
    _migrate(db)
    db.commit()  # make tables visible to the seed connection
    seed_from_json()
    db.close()


def _migrate(db):
    # Existing columns on fyndnote_projects (dialect-aware).
    if DATABASE_TYPE == "sqlite":
        existing = {
            r["name"]
            for r in db.execute("PRAGMA table_info(fyndnote_projects)").fetchall()
        }
    else:
        existing = {
            r["column_name"]
            for r in db.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_name='fyndnote_projects'"
            ).fetchall()
        }

    # Migrations for existing databases that lack these columns.
    for col, coltype in [
        ("color", "TEXT DEFAULT '#1976d2'"),
        ("tags", "TEXT DEFAULT ''"),
        ("instructions", "TEXT DEFAULT ''"),
        ("ml_enabled", "INTEGER DEFAULT 0"),
        ("ml_url", "TEXT DEFAULT ''"),
        ("ml_annotator", "TEXT DEFAULT ''"),
        ("ml_mode", "TEXT DEFAULT 'on_navigate'"),
    ]:
        if col not in existing:
            db.execute(f"ALTER TABLE fyndnote_projects ADD COLUMN {col} {coltype}")


def seed_from_json():
    import json

    seed_file = DATABASE_PATH.parent / "users.json"
    if not seed_file.exists():
        return
    db = get_db()
    existing = db.execute("SELECT COUNT(*) FROM fyndnote_users").fetchone()[0]
    if existing > 0:
        db.close()
        return
    if DATABASE_TYPE == "sqlite":
        db.execute("PRAGMA foreign_keys=OFF")
    else:
        # Disable FKs while seeding. Requires a superuser PG role (the default
        # `postgres` role is). Fall back gracefully for non-superuser roles so
        # seeding still inserts what it can instead of aborting the whole seed.
        try:
            db.execute("SET session_replication_role = replica")
        except Exception:
            pass
    data = json.loads(seed_file.read_text())
    for user in data["users"]:
        db.execute(
            "INSERT OR IGNORE INTO fyndnote_users (id, name, global_role) VALUES (?, ?, ?)",
            (user["id"], user["name"], user["global_role"]),
        )
        for project_id, role in user.get("project_roles", {}).items():
            db.execute(
                "INSERT OR IGNORE INTO fyndnote_project_permissions (user_id, project_id, role) VALUES (?, ?, ?)",
                (user["id"], project_id, role),
            )
    db.commit()
    if DATABASE_TYPE == "sqlite":
        db.execute("PRAGMA foreign_keys=ON")
    else:
        db.execute("SET session_replication_role = origin")
    db.close()
